# Generated by Django 4.1.5 on 2023-03-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlevelperm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_gps',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(default='admin', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
