# Generated by Django 4.1.5 on 2023-03-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlevelperm', '0002_user_created_gps_user_device_id_user_firebase_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': ()},
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.PositiveBigIntegerField(choices=[(1, 'Individual'), (2, 'Business')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.PositiveBigIntegerField(choices=[(1, 'Mr'), (2, 'Mrs')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
