# Generated by Django 4.1.5 on 2023-03-02 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlevelperm', '0003_alter_user_options_user_account_type_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('residenceStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userlevelperm.residencestatus')),
            ],
        ),
    ]
