# Generated by Django 4.1.5 on 2023-03-03 10:56

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('userlevelperm', '0006_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.AddField(
            model_name='apierrorlog',
            name='errorMsg',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='WelcomePages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.ForeignKey(on_delete=django.db.models.aggregates.Aggregate, to='userlevelperm.pages')),
            ],
        ),
    ]
