# Generated by Django 4.1.5 on 2023-03-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlevelperm', '0007_pages_apierrorlog_errormsg_welcomepages'),
    ]

    operations = [
        migrations.AddField(
            model_name='apierrorlog',
            name='label',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='apierrorlog',
            name='platform',
            field=models.CharField(default='', max_length=255),
        ),
    ]
