# Generated by Django 4.1.5 on 2023-03-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlevelperm', '0008_apierrorlog_label_apierrorlog_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='apierrorlog',
            name='log',
            field=models.CharField(default='', max_length=255),
        ),
    ]
