# Generated by Django 4.1.5 on 2023-03-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlevelperm', '0010_alter_apierrorlog_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='apierrorlog',
            name='funcName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
