# Generated by Django 4.1.5 on 2023-03-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlevelperm', '0011_apierrorlog_funcname'),
    ]

    operations = [
        migrations.AddField(
            model_name='apierrorlog',
            name='device_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
