# Generated by Django 4.1.5 on 2023-03-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlevelperm', '0012_apierrorlog_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='url',
        ),
        migrations.AddField(
            model_name='banners',
            name='image',
            field=models.ImageField(default='info.png', upload_to='media'),
        ),
    ]
